# 网站标题
title: arloou
# 网站标题后缀
suffix: website
# 作者名称(会显示在首页文章下面)
author: Luzz
# 首页简介（显示在首页顶部Logo的那句话）
home_describe: 一個無聊的網站
# 网站关键字
keyword: luzz,arloou,blog
is_article_img: true  #false是否开启文章背景图显示(随机图片)
# 网站描述
web_description: 描述
# 导航名称
menus_title:
  home: 首頁
  archive: 歸檔
  categories: 分類
  tags: 標籤
  links: 鏈接
  about: 關於
# 导航 （不建议修改）
menus:
  home: /
  categories: /categories
  tags: /tags
  archive: /archives
  about: /about

# logo
logo: https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/avatar.png
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面上面的图表
topIcon:
  homeIcon: "https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/drink_tea.png"
  categoriesIcon: "https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/milktea_icon.png"
  archivesIcon: "https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/wine_icon.png"
  tagIcon: "https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/juhua_icon.png"
  linksIcon: "https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/avatar.png"
  
  
# 标签页显示多少个标签
tagsNum: 1000
# 网页访问统计
web_analytics:  
  enable: false #需要改为true
  baidu: 4b5fe1472f22fa  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    name: 'email',
    iconLink: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/email-fill.png',
    toUrl: 'mailto:arloou@gmail.com'
  }
  # - {
  #   #描述名称
  #   name: 'Github',
  #   #图标    
  #   iconLink: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/github-fill.png',
  #   #跳转链接    
  #   toUrl: 'https://github.com/luzizheng'
  # }
  # - {
  #   name: '微博',
  #   iconLink: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/weibo-circle-fill.png',
  #   toUrl: 'https://weibo.com/u/1806986113'
  # }
  # - {
  #   name: 'Instagram', 
  #   iconLink: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/instagram-fill.png',  
  #   toUrl: 'https://www.instagram.com/luzizheng/'
  # }
  # - {
  #   name: '知乎',  
  #   iconLink: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/zhihu-circle-fill.png', 
  #   toUrl: 'https://www.zhihu.com/people/frank-lu-73'
  # }
  # - {
  #   name: '微信',  
  #   iconLink: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/WeChat.png', 
  #   toUrl: ''
  # } 
  # - {
  #   name: '网易云音乐',
  #   iconLink: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/neteasymusic_icon.png',
  #   toUrl: 'https://music.163.com/#/user/home?id=18065540'
  # }
  
# 友情链接
linksList:
  - {
    title: 'Gmail',
    intro: 'arloou@gmail.com',
    link: 'mailto:arloou@gmail.com',
    image: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/Mail.png'
  }
  - {
    title: '微信',
    intro: '@arloou',
    link: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/2241638164989_.pic.jpg',
    image: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/social-wechat.png'
  }
  - {
    title: '新浪微博',
    intro: '@_Luzz_',
    link: 'https://weibo.com/u/1806986113/',
    image: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/social-weibo.png'
  }
  - {
    title: 'GitHub',
    intro: '@luzizheng',
    link: 'https://github.com/luzizheng',
    image: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/social-github.png'
  }
  - {
    title: 'Instagram',
    intro: '@luzizheng',
    link: 'https://www.instagram.com/luzizheng/',
    image: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/Instagram-Logo.png'
  }
  - {
    title: 'Bandcamp',
    intro: '@luzz0616',
    link: 'https://bandcamp.com/luzz0616',
    image: 'https://cdn.jsdelivr.net/gh/luzizheng/images@master/img/bandcamp.png'
  }
# 文字内点击图片放大相关配置
picture:
  # 蒙版的颜色也就是 打开图片背景 显示的颜色
  colour: '#FFFDD0'
  # 透明度
  opacity: 0.5
  # 图片角度 就是显示图片的角度
  imgRadius: "10px"
#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
default_cover: https://api.ixiaowai.cn/gqapi/gqapi.php